### PR TITLE
chore: Update pythonanywhere-deploy-action to latest version

### PR DESCRIPTION
**Pull request by umuttopalak**

### CODE REVIEW

**Comment by umuttopalak** [comment]
I can fix your deployment if you contact me @Magudeshgit

**Comment by Magudeshgit** [comment]
> I can fix your deployment if you contact me @Magudeshgit 

Hey there, thank you for your fix, I meddled with actions for pythonaywhere a while ago, and I just left it unfinished. 

Your Changes have been noted, Thank You.

**Comment by umuttopalak** [comment]
> > I can fix your deployment if you contact me @Magudeshgit
> 
> Hey there, thank you for your fix, I meddled with actions for pythonaywhere a while ago, and I just left it unfinished.
> 
> Your Changes have been noted, Thank You.

Did that changes worked can you check and tell me im trying to improve action

**Comment by Magudeshgit** [comment]
> > > I can fix your deployment if you contact me @Magudeshgit
> > 
> > 
> > Hey there, thank you for your fix, I meddled with actions for pythonaywhere a while ago, and I just left it unfinished.
> > Your Changes have been noted, Thank You.
> 
> Did that changes worked can you check and tell me im trying to improve action
@umuttopalak 
Yes it indeed did, but I just figured out that the whole thing only works when the pythonanywhere console is connected via browser additonally. 

I also did a bit of digging and found out that pythonanywhere doesn't provide any api for it, and only connecting via browser will work. But it would be better if the actions work without the console being opened.

I have brainstormed a basic idea on how we could accomplish this, feel free to contact me. I'll explain my idea to you in detail. 

Instagram: magudesh.dev
Mail: magudeshofficial@gmail.com
LinkedIn : linkedin.com/in/magudesh-k-9325852b6/


Or if you decide to stay the course, it's my kind opinion to mention that this works only with browser console open in your documentations and elsewhere.

Thank you

**Pull request merged**
